version: '3.7'

services:

  postcodechecker:
    container_name: postcodechecker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/client'
      - '/client/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development